alias vim=nvim
alias v=nvim
alias quit=exit
alias :q=quit
alias syrin=~/Tools/'Syrinscape\ Online\ Player'/'Syrinscape\ Online\ Player &'
alias or='python3 ~/Tools/dnd/owlbear.py'
alias ai='sudo apt -y install'
alias logout='/usr/bin/gnome-session-quit --no-prompt'
alias z='firefox zoom.us/my/johnlindon &'
alias ani-cli='~/Tools/ani-cli/ani-cli'
alias python='python3'
alias copy="xclip -sel clip"
alias pgen="pwgen -ysBv 128 1"
alias gitswitch="~/scripts/gitswitch.sh"
alias "v."="nvim ."
alias "vp"="v $currentproject"
alias "vph"="currentproject=pwd"
alias ya="youtube-dl -x --audio-format mp3 "
alias vw="nvim ~/vimwiki/index.wiki"
alias vimwiki=vw
